export const meta = {
  name: 'gawaah-web-all-six',
  description: 'Fix the camera start gesture and surface all six capabilities in the web client, wired to the brain',
  phases: [
    { title: 'Web', detail: '5 agents: camera+shell, MUDRA+PEEL panels, CHILLA+SAAF panels, brain bridge, visual proof' },
  ],
}

const ROOT = '/Users/agnik/Desktop/razor'

const BASE = [
  'GAWAAH — a camera-native kirana counter. Repo: ' + ROOT,
  'Python: ' + ROOT + '/.venv/bin/python    JS selftests: cd ' + ROOT + ' && node web/selftest.mjs',
  'STATE: 1599 Python tests + 203 JS selftests pass. 18 modules. Lint clean.',
  '',
  'THE PROBLEM YOU ARE FIXING: the web client implements ONLY the core billing loop.',
  'Five capabilities exist as fully-tested Python modules on the brain but have ZERO UI:',
  '  gawaah/mudra.py        OccluderGesture(ref).update(rect)->GestureState(NONE/OPEN/FIST/GOODS/AMBIGUOUS,',
  '                         solidity, defects, compactness, area_mm2)   -- hand read as an OCCLUDER, no model',
  '  gawaah/ident_sticker.py StickerRegistry(dir).enrol(name,crop) / .compare(name,crop)->StickerVerdict(',
  '                         ignited_fraction, verdict GENUINE|TAMPERED|UNREGISTERABLE, ecc_ok, reason)',
  '  gawaah/chilla.py       ScreenFinder.detect(rect); LedgerMatcher(mirror,window_s).match(amount_paise,ts)',
  '                         ->MatchResult(verdict MATCHED|NO_MATCH|AMBIGUOUS|AMBER_STALE, candidates, reason)',
  '  gawaah/saaf.py         BurstStacker.stack(frames)->StackResult(image, used, rejected, sharpness_gain, warning)',
  '  gawaah/brain.py        Brain(config).ingest_frame(frame, ts)->BrainState ; .done() ; .on_webhook(raw,sig)',
  '                         BrainState: mat_lock, placements, basket lines (integer paise), total_paise,',
  '                         amber items (EXCLUDED from total), session state, exceptions, audit head hash',
  '',
  'EXISTING WEB CLIENT (web/):',
  '  index.html  77 lines   #chrome #lock #fps #banner #cam(video) #raw(canvas) #rect(canvas)',
  '                         #lockdetail #total #amber #ack(button) #done(button) #reason #cvstat',
  '  app.js      1323 lines ES module, 72 exports. Pure-function core: geometry (3x3 homographies in plain',
  '                         JS, no OpenCV needed), a state reducer, integer-paise totals, MoneyError,',
  '                         Reason.* codes, loadOpenCV() from ./vendor/opencv.js (NOW VENDORED, 11,386,540',
  '                         bytes, pinned 4.11.0-release.1), dispatch({type:...}), adjudicateLock().',
  '  style.css   184 lines',
  '  selftest.mjs 1899 lines, 203 node tests, all passing. RUN IT AFTER EVERY CHANGE.',
  '  vendor/opencv.js  present',
  '',
  'INVARIANTS THE WEB CLIENT MUST NOT BREAK:',
  '3. ZERO model weights in the browser. Geometry only. Never fetch a model.',
  '4. The mask is applied AT FRAME GRAB: only the rectified mat crop is kept or sent. The split preview',
  '   (raw | rectified) exists to make that visible. Never send an unmasked frame anywhere.',
  '7. Abstain rather than guess. Every panel must have a visible "I do not know" state with a named reason.',
  '   No panel may ever show GREEN -- green comes only from a signature-verified webhook.',
  '2. No feature may turn the counter green. MUDRA reveals a target, PEEL warns, CHILLA corroborates,',
  '   SAAF selects frames. None of them decide money.',
  '',
  'RULES: You own ONLY your listed files. Other agents edit other files concurrently.',
  'No git write commands, no pip/npm install, no network fetches at runtime.',
  'RUN `node web/selftest.mjs` after every change and keep all 203 passing (add more).',
  'Never report a test you did not run. Do not weaken a test to make it pass.',
].join('\n')

const S = {
  type: 'object',
  properties: {
    task: { type: 'string' },
    files_changed: { type: 'array', items: { type: 'string' } },
    what_a_user_now_sees: { type: 'string', description: 'concretely, what is on screen that was not before' },
    selftests_passing: { type: 'number' },
    test_output_tail: { type: 'string' },
    abstention_states: { type: 'array', items: { type: 'string' }, description: 'every visible I-do-not-know state you added' },
    invariants_respected: { type: 'string' },
    honest_limits: { type: 'array', items: { type: 'string' } },
  },
  required: ['task', 'files_changed', 'what_a_user_now_sees', 'selftests_passing', 'test_output_tail', 'abstention_states', 'invariants_respected', 'honest_limits'],
}

const JOBS = [
  { k: 'camera-shell', files: 'web/index.html + web/style.css', brief: [
    'FIX THE BLACK SCREEN, AND BUILD THE SHELL THAT HOLDS ALL SIX CAPABILITIES.',
    '',
    'BUG (confirmed by a real screenshot): both preview panes render black. getUserMedia is called at',
    'app.js:1069 but there is NO START BUTTON -- the only buttons are #done and #ack. Browsers require a',
    'user gesture before granting camera, so on a laptop the call never yields a stream and the app sits',
    'in NO LOCK forever with two black rectangles and no explanation.',
    'FIX: add a prominent START CAMERA control that is the first thing a visitor sees, plus a clear',
    'permission-denied / no-camera state that explains what happened. The app must never show two silent',
    'black boxes again. (app.js is owned by another agent -- expose the button as #start and document the',
    'contract in a comment; that agent wires the listener.)',
    '',
    'THEN build the SHELL for six capabilities. A left rail or tab strip with six entries:',
    '  CORE (billing) · MUDRA (gesture) · PEEL (sticker) · CHILLA (screen) · SAAF (enrolment) · LEDGER (audit)',
    'Each gets a panel container with a stable id (#panel-core, #panel-mudra, #panel-peel, #panel-chilla,',
    '#panel-saaf, #panel-ledger) that other agents fill. Only one panel visible at a time; CORE is default.',
    'Each rail entry shows a small live status dot: OK / ABSTAIN / OFF.',
    '',
    'DESIGN: this is a shop counter tool, dark, high contrast, readable at arm length under a tube light.',
    'Tabular numerals for every rupee figure. The counter chrome colour follows session state',
    '(amber = nothing authorised, green = settled, red = mismatch). Make AMBER visually dominant -- the',
    'thesis of the product is that it says "I do not know" more often than it says yes.',
    'Keep it dependency-free. No CSS framework, no icon font, no webfont (CSP blocks external hosts).',
  ].join('\n') },

  { k: 'app-core', files: 'web/app.js', brief: [
    'WIRE THE CAMERA AND THE SIX-PANEL ROUTER. You own app.js.',
    '',
    '1. START GESTURE: bind a click on #start (added by the shell agent) to the existing camera path.',
    '   Handle every failure explicitly and visibly: NotAllowedError (permission denied),',
    '   NotFoundError (no camera), NotReadableError (camera busy), and insecure-context. Each must show a',
    '   named reason in #reason, never a silent black pane. Add Reason codes for each.',
    '2. Prefer the rear camera (facingMode environment) but fall back to any camera, and SAY which one is',
    '   in use -- on a laptop it will be the front camera and the mat will not lock, which is correct and',
    '   must be explained rather than looking broken.',
    '3. PANEL ROUTER: a tiny hash-router or click router over #panel-* containers, exporting a pure',
    '   function selectPanel(state, id) -> newState so it is unit-testable in selftest.mjs.',
    '4. BRAIN BRIDGE: a WebSocket client to ws://<host>:8787 with exponential-backoff reconnect. Export a',
    '   pure reducer for connection state (CONNECTING/OPEN/RETRYING/OFFLINE) with a visible banner.',
    '   When offline, the UI must show PENDING_OFFLINE and continue billing locally while authorising',
    '   nothing. Frames sent to the brain must be the RECTIFIED CROP ONLY (invariant 4) -- assert this in',
    '   code and in a selftest.',
    '5. Expose a documented panel API other agents use: registerPanel(id, {onState, onFrame}) so the',
    '   MUDRA/PEEL/CHILLA/SAAF agents can attach without editing your file. Write it, document it in a',
    '   comment block, and add selftests for it.',
    'Keep all 203 existing selftests green and add tests for everything above.',
  ].join('\n') },

  { k: 'mudra-peel-ui', files: 'web/panels/mudra.js + web/panels/peel.js + web/panels/panels.test.mjs', brief: [
    'BUILD THE MUDRA AND PEEL PANELS as ES modules that attach via the panel API in app.js',
    '(registerPanel(id, {onState, onFrame})). If that API does not exist yet, define the same shape',
    'yourself and export it -- the app agent is building the matching side concurrently.',
    '',
    'MUDRA PANEL (#panel-mudra): the hand read as an OCCLUDER, no model, no MediaPipe (7.8MB model file is',
    'structurally forbidden -- 1.63x the whole cold-load budget).',
    'Show LIVE: the current state (NONE/OPEN/FIST/GOODS/AMBIGUOUS), the measured solidity as a number AND',
    'as a horizontal gauge with the calibrated thresholds drawn on it, the convexity-defect count, and',
    'the area in mm2. Reference values from real hands: fist ~0.73, open palm ~0.92, goods 0.96-1.00.',
    'AMBIGUOUS must be visually loud -- it is a first-class outcome, not an error.',
    'Show the pay-panel ROI on the rectified view, and a clear "panel blocked" state when goods overlap it.',
    'The panel REVEALS a pre-minted payment target; it must never mint or green. Say so in the UI.',
    '',
    'PEEL PANEL (#panel-peel): sticker destination check. NO QR LIBRARY -- no encoder, no decoder, no',
    'module-grid reconstruction. It is a PIXEL DIFF against an enrolled photograph.',
    'Show: the enrolled crop next to the fresh crop, the ignited-pixel fraction as a number and a bar,',
    'and the verdict GENUINE / TAMPERED / UNREGISTERABLE. An unenrolled sticker is GREY and must NEVER be',
    'called tampered -- falsely accusing a shopkeeper of fraud on camera is the worst failure this product',
    'has. Include an ENROL action and a visible list of enrolled slots.',
    'Display the measured ECC benefit honestly if the brain reports it (with ECC a 1px shift gives ~0.4%',
    'ignited; without ECC the same shift gives ~16% -- a naive diff is a false-accusation machine).',
    '',
    'Both panels: pure render functions taking a state object and returning DOM, so panels.test.mjs can',
    'unit-test them with no browser. Run: cd ' + ROOT + ' && node web/panels/panels.test.mjs',
  ].join('\n') },

  { k: 'chilla-saaf-ui', files: 'web/panels/chilla.js + web/panels/saaf.js + web/panels/ledger.js + web/panels/panels2.test.mjs', brief: [
    'BUILD THREE PANELS as ES modules attaching via registerPanel(id, {onState, onFrame}).',
    '',
    'CHILLA PANEL (#panel-chilla): check a customer PAYMENT SUCCESSFUL screen against the ledger.',
    'The core honesty: we do NOT read the transaction reference. At this rig a UPI reference digit stroke',
    'is 0.19mm = 0.54px against a 2px Nyquist floor -- it is not hard to read, it is NOT IN THE SIGNAL.',
    'We match on (amount, time window) instead. Put that sentence in the panel, visibly.',
    'Show: the detected screen quad on the rectified view, the amount read, the ledger window being',
    'searched, and the verdict MATCHED / NO_MATCH / AMBIGUOUS / AMBER_STALE.',
    'HARD RULE, render it as such: this panel can NEVER show green and can NEVER show red-as-fraud.',
    'NO_MATCH is AMBER. A stale mirror is AMBER even when a match exists. More than one payment matching',
    'the amount in the window is AMBIGUOUS, never a confident match. Show the collision risk number.',
    '',
    'SAAF PANEL (#panel-saaf): the enrolment frame gate. Invisible by construction, so make it legible.',
    'Show a contact sheet of the burst frames with each frame REJECTED or KEPT and why (blur below floor,',
    'saturation above the guard), the measured sharpness gain, and the WARNING state when inter-frame',
    'motion is near zero (no sub-pixel diversity -> stacking degenerates to denoising, and the honest',
    'behaviour is to say so rather than return a worse image silently).',
    '',
    'LEDGER PANEL (#panel-ledger): the audit chain. Show the head hash, the line count, and the last N',
    'entries with their module, reason code and money action. Add a VERIFY button that re-checks the chain',
    'and shows VERIFIED or the exact line where it breaks. This is the panel a judge will click.',
    '',
    'All three: pure render functions taking state and returning DOM, unit-tested with no browser.',
    'Run: cd ' + ROOT + ' && node web/panels/panels2.test.mjs',
  ].join('\n') },

  { k: 'brain-ws', files: 'gawaah/brain_server.py + tests/test_brain_server.py', brief: [
    'THE BRIDGE. The web client has no server to talk to. Build it.',
    '',
    'gawaah/brain_server.py: a FastAPI + uvicorn process on port 8787 that owns a Brain instance and',
    'serves the web client over WebSocket.',
    'Protocol (document it in a module docstring):',
    '  client -> server : {type:"frame", rect: <base64 PNG of the RECTIFIED CROP ONLY>, ts: <iso>}',
    '                     {type:"done"} {type:"revert", item_id} {type:"ack"}',
    '                     {type:"enrol_sticker", name} {type:"select_panel", id}',
    '  server -> client : {type:"state", ...BrainState as JSON...} sent on every change',
    '                     {type:"mudra", state, solidity, defects, area_mm2}',
    '                     {type:"peel", name, ignited_fraction, verdict, ecc_ok}',
    '                     {type:"chilla", verdict, amount_paise, candidates, reason}',
    '                     {type:"saaf", used, rejected, sharpness_gain, warning}',
    '                     {type:"ledger", head, count}',
    'INVARIANT 4 IS LOAD-BEARING HERE: the server must REFUSE a frame that is not the expected rectified',
    'buffer shape (840x1188) and log the refusal. It must never accept a raw camera frame. Test that.',
    'INVARIANT 5: this server does NOT hold Razorpay secrets and does NOT mint. It calls paisa for money.',
    'Also serve the static web/ directory so one command runs the whole thing.',
    'Add a --sim flag that drives synthetic frames when no camera is connected, so the whole UI can be',
    'demonstrated on a laptop with no hardware -- this is what makes the six panels filmable.',
    'TESTS: use fastapi TestClient websocket_connect. Assert the protocol, assert a wrong-shape frame is',
    'refused, assert no secret ever appears in any message, assert the state message carries integer paise.',
  ].join('\n') },
]

phase('Web')
log('5 agents: camera fix + six-panel shell, app router/bridge, MUDRA+PEEL, CHILLA+SAAF+LEDGER, brain WebSocket server.')

const out = (await parallel(JOBS.map(j => () =>
  agent(BASE + '\n\n=== YOUR FILES (you own these and ONLY these) ===\n' + j.files +
    '\n\n=== YOUR TASK ===\n' + j.brief +
    '\n\nBuild it, run the tests, iterate until green, report real output.',
    { label: 'web:' + j.k, phase: 'Web', schema: S })
))).filter(Boolean)

return {
  panels: out.map(o => ({ task: o.task, files: o.files_changed, sees: o.what_a_user_now_sees, tests: o.selftests_passing })),
  abstentions: out.flatMap(o => (o.abstention_states || []).map(a => (o.task || '').slice(0, 18) + ': ' + a)),
  limits: out.flatMap(o => (o.honest_limits || []).map(a => (o.task || '').slice(0, 18) + ': ' + a)),
}
